import {
  collaborationAckInbox,
  emailAcknowledgeInbox,
  collaborationAwardNetworkBid,
  collaborationRetryNetworkDeliveries,
  collaborationControlTask,
  collaborationDecideApproval,
  collaborationSideEffectApprove,
  collaborationSideEffectCreate,
  collaborationSideEffectComplete,
  collaborationSideEffectCancel,
  collaborationExecute,
  collaborationWorkflowExecute,
  collaborationWorkflowPropose,
  collaborationWorkflowStatus,
  collaborationWorkflowControl,
  collaborationPropose,
  collaborationRequestApproval,
  collaborationSetNetworkPeerTrust,
  collaborationAddNetworkTrustRoot,
  collaborationRevokeNetworkTrustRoot,
  collaborationGrantDelegation,
  collaborationRevokeDelegation,
  collaborationAddOrganizationMember,
  collaborationRemoveOrganizationMember,
  collaborationAddRoomMember,
  collaborationRemoveRoomMember,
  collaborationGetIdentity,
  collaborationUpdateIdentity,
  collaborationRegisterNetworkPeer,
  collaborationSnapshot,
  collaborationOnUpdate,
  collaborationProposeNetworkService,
  collaborationNegotiateNetworkCapability,
  collaborationRevokeNetworkCapabilityAgreement,
  collaborationPublishNetworkOffer,
  collaborationSubmitNetworkBid,
  collaborationFederatedRoomGrants,
  collaborationIssueFederatedRoomGrant,
  collaborationRevokeFederatedRoomGrant,
  type CollaborationExecutionHandle,
  type CollaborationSnapshot,
} from "@/lib/agent/pi-client";

export type { CollaborationExecutionHandle, CollaborationSnapshot, CollaborationTaskHandle, CollaborationUpdate } from "@/lib/agent/pi-client";

export const assistantFacade = {
  snapshot: (): Promise<CollaborationSnapshot> => collaborationSnapshot(),
  onUpdate: collaborationOnUpdate,
  propose: (input: Parameters<typeof collaborationPropose>[0]) => collaborationPropose(input),
  execute: (taskId: string): Promise<CollaborationExecutionHandle> => collaborationExecute(taskId),
  proposeWorkflow: (input: Parameters<typeof collaborationWorkflowPropose>[0]) => collaborationWorkflowPropose(input),
  executeWorkflow: (workflowId: string) => collaborationWorkflowExecute(workflowId),
  workflowStatus: (workflowId: string) => collaborationWorkflowStatus(workflowId),
  controlWorkflow: (input: Parameters<typeof collaborationWorkflowControl>[0]) => collaborationWorkflowControl(input),
  ackInbox: (eventId: string) => collaborationAckInbox(eventId),
  ackEmailInbox: (accountId: string, threadId: string, messageDate?: string) => (emailAcknowledgeInbox as (accountId: string, threadId: string, messageDate?: string) => ReturnType<typeof emailAcknowledgeInbox>)(accountId, threadId, messageDate),
  requestApproval: (input: Parameters<typeof collaborationRequestApproval>[0]) => collaborationRequestApproval(input),
  decideApproval: (input: Parameters<typeof collaborationDecideApproval>[0]) => collaborationDecideApproval(input),
  approveSideEffect: (intentId: string) => collaborationSideEffectApprove(intentId),
  createSideEffect: (input: Parameters<typeof collaborationSideEffectCreate>[0]) => collaborationSideEffectCreate(input),
  completeSideEffect: (intentId: string, receipt?: string) => collaborationSideEffectComplete(intentId, receipt),
  cancelSideEffect: (intentId: string, reason?: string) => collaborationSideEffectCancel(intentId, reason),
  controlTask: (input: Parameters<typeof collaborationControlTask>[0]) => collaborationControlTask(input),
  setNetworkPeerTrust: (peerId: string, trust: Parameters<typeof collaborationSetNetworkPeerTrust>[1]) => collaborationSetNetworkPeerTrust(peerId, trust),
  addNetworkTrustRoot: (publicKeyPem: string) => collaborationAddNetworkTrustRoot(publicKeyPem),
  revokeNetworkTrustRoot: (keyRef: string) => collaborationRevokeNetworkTrustRoot(keyRef),
  grantDelegation: (input: Parameters<typeof collaborationGrantDelegation>[0]) => collaborationGrantDelegation(input),
  revokeDelegation: (delegationId: string) => collaborationRevokeDelegation(delegationId),
  addOrganizationMember: (input: Parameters<typeof collaborationAddOrganizationMember>[0]) => collaborationAddOrganizationMember(input),
  removeOrganizationMember: (input: Parameters<typeof collaborationRemoveOrganizationMember>[0]) => collaborationRemoveOrganizationMember(input),
  getIdentity: () => collaborationGetIdentity(),
  updateIdentity: (input: Parameters<typeof collaborationUpdateIdentity>[0]) => collaborationUpdateIdentity(input),
  addRoomMember: (input: Parameters<typeof collaborationAddRoomMember>[0]) => collaborationAddRoomMember(input),
  removeRoomMember: (input: Parameters<typeof collaborationRemoveRoomMember>[0]) => collaborationRemoveRoomMember(input),
  registerNetworkPeer: (input: Parameters<typeof collaborationRegisterNetworkPeer>[0]) => collaborationRegisterNetworkPeer(input),
  submitNetworkBid: (input: Parameters<typeof collaborationSubmitNetworkBid>[0]) => collaborationSubmitNetworkBid(input),
  proposeNetworkService: (input: Parameters<typeof collaborationProposeNetworkService>[0]) => collaborationProposeNetworkService(input),
  negotiateNetworkCapability: (input: Parameters<typeof collaborationNegotiateNetworkCapability>[0]) => collaborationNegotiateNetworkCapability(input),
  revokeNetworkCapabilityAgreement: (agreementId: string, reason: string) => collaborationRevokeNetworkCapabilityAgreement(agreementId, reason),
  publishNetworkOffer: (input: Parameters<typeof collaborationPublishNetworkOffer>[0]) => collaborationPublishNetworkOffer(input),
  awardNetworkBid: (bidId: string) => collaborationAwardNetworkBid(bidId),
  retryNetworkDeliveries: () => collaborationRetryNetworkDeliveries(),
  federatedRoomGrants: () => collaborationFederatedRoomGrants(),
  issueFederatedRoomGrant: (input: Parameters<typeof collaborationIssueFederatedRoomGrant>[0]) => collaborationIssueFederatedRoomGrant(input),
  revokeFederatedRoomGrant: (grantId: string) => collaborationRevokeFederatedRoomGrant(grantId),
} as const;

export type AssistantFacade = typeof assistantFacade;
