import { _electron as electron } from "playwright";
import { mkdirSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const userData = mkdtempSync(join(tmpdir(), "dbg-"));
mkdirSync(join(userData, "pi-agent"), { recursive: true });
const app = await electron.launch({ args: [`--user-data-dir=${userData}`, root], executablePath: join(root, "node_modules", ".bin", "electron"), cwd: root, env: { ...process.env, ELECTRON_RENDERER_URL: "", OPENBUDDY_DEBUG_UI: "0" } });
const page = await app.firstWindow();
await page.waitForFunction(() => Boolean(window.api?.apiVersion === 1), undefined, { timeout: 40000 });
await new Promise(r => setTimeout(r, 2500));
console.log("BEFORE:", await page.evaluate(() => ({ hasComposer: Boolean(document.querySelector("textarea.wb-composer__input")), theme: document.documentElement.getAttribute("data-theme"), name: document.documentElement.getAttribute("data-theme-name") })));
await page.evaluate(() => { window.localStorage.setItem("openbuddy.onboarding.state", JSON.stringify({version:1,status:"done",index:0,steps:[],startedAt:Date.now(),updatedAt:Date.now(),completedAt:Date.now()})); window.localStorage.setItem("openbuddy.tour.state","seen"); });
await page.reload({ waitUntil: "domcontentloaded" });
await page.waitForFunction(() => Boolean(window.api?.apiVersion === 1), undefined, { timeout: 40000 });
await new Promise(r => setTimeout(r, 2500));
console.log("AFTER RELOAD:", await page.evaluate(() => ({ hasComposer: Boolean(document.querySelector("textarea.wb-composer__input")), theme: document.documentElement.getAttribute("data-theme"), name: document.documentElement.getAttribute("data-theme-name"), bodyText: document.body.innerText.slice(0,200) })));
await page.evaluate(() => { window.localStorage.setItem("openbuddy.theme","openbuddy-dark"); window.localStorage.setItem("openbuddy.theme.name","openbuddy-dark"); window.localStorage.setItem("openbuddy.theme.mode","manual"); });
await page.reload({ waitUntil: "domcontentloaded" });
await page.waitForFunction(() => Boolean(window.api?.apiVersion === 1), undefined, { timeout: 40000 });
await new Promise(r => setTimeout(r, 2500));
console.log("AFTER THEME:", await page.evaluate(() => ({ hasComposer: Boolean(document.querySelector("textarea.wb-composer__input")), theme: document.documentElement.getAttribute("data-theme"), name: document.documentElement.getAttribute("data-theme-name"), lsTheme: window.localStorage.getItem("openbuddy.theme.name"), bodyText: document.body.innerText.slice(0,300) })));
await app.close();
