import { lstat, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
vi.mock("electron", () => ({ app: { getPath: () => "/tmp/openbuddy-marketplace-advanced-test" }, safeStorage: { isEncryptionAvailable: () => false } }));
vi.mock("../casdoor/casdoor-auth", () => ({ casdoorAuth: { status: () => ({ config: { configured: false }, identity: null, tenantContext: { activeTenantId: undefined } }) } }));
const originalPiHome = process.env.PI_HOME;
afterEach(() => { if (originalPiHome === undefined) delete process.env.PI_HOME; else process.env.PI_HOME = originalPiHome; });
async function setup(home: string, plugin = "demo", version = "1.0.0") { process.env.PI_HOME = home; const source = await mkdtemp(join(tmpdir(), "openbuddy-marketplace-advanced-source-")); const pluginRoot = join(source, "plugins", plugin); await mkdir(pluginRoot, { recursive: true }); await writeFile(join(pluginRoot, "package.json"), JSON.stringify({ name: plugin, version })); const resources = await import("../pi-resources"); await resources.marketplaceAddSource(source); return { resources, source, pluginRoot, targetRoot: join(home, ".openbuddy", "agent", "plugins", plugin), index: join(home, ".openbuddy", "agent", "marketplace-installed.json") }; }
async function install(resources: any, source: string, plugin = "demo") { await resources.marketplaceAction({ type: "install", sourceUrlOrPath: source, pluginRelativePath: plugin }); }
describe("marketplace advanced POSIX rollback contracts", () => {
  it("rolls back after verification failure", async () => { const home = await mkdtemp(join(tmpdir(), "marketplace-advanced-home-")); const { resources, source, pluginRoot, targetRoot, index } = await setup(home); await install(resources, source); await writeFile(join(targetRoot, "old.txt"), "old"); await writeFile(join(pluginRoot, "package.json"), "invalid-json"); await expect(install(resources, source)).rejects.toThrow(); await expect(readFile(join(targetRoot, "old.txt"), "utf8")).resolves.toBe("old"); await expect(readFile(index, "utf8")).resolves.toContain("demo"); });
  it("restores managed directory after trust failure", async () => { const home = await mkdtemp(join(tmpdir(), "marketplace-advanced-home-")); const { resources, source, pluginRoot, targetRoot } = await setup(home); await install(resources, source); await writeFile(join(targetRoot, "state"), "before"); await writeFile(join(pluginRoot, "package.json"), "{broken"); await expect(resources.marketplaceAction({ type: "update", sourceUrlOrPath: source, pluginRelativePath: "demo" })).rejects.toThrow(); expect(await readFile(join(targetRoot, "state"), "utf8")).toBe("before"); });
  it("makes same-version install idempotent", async () => { const home = await mkdtemp(join(tmpdir(), "marketplace-advanced-home-")); const { resources, source, index } = await setup(home); await install(resources, source); const before = JSON.parse(await readFile(index, "utf8")).plugins; await install(resources, source); const after = JSON.parse(await readFile(index, "utf8")).plugins; const normalize = (plugins: Record<string, { installedAt?: string; [key: string]: unknown }>) => Object.fromEntries(Object.entries(plugins).map(([key, value]) => [key, { ...value, installedAt: "normalized" }])); expect(normalize(after)).toEqual(normalize(before)); });
  it("replaces the index entry for a new version", async () => { const home = await mkdtemp(join(tmpdir(), "marketplace-advanced-home-")); const { resources, source, pluginRoot, index } = await setup(home); await install(resources, source); await writeFile(join(pluginRoot, "package.json"), JSON.stringify({ name: "demo", version: "2.0.0" })); await install(resources, source); expect(Object.keys(JSON.parse(await readFile(index, "utf8")).plugins)).toHaveLength(1); });
  it("preserves metadata when uninstall target is unmanaged", async () => { const home = await mkdtemp(join(tmpdir(), "marketplace-advanced-home-")); const { resources, source, targetRoot, index } = await setup(home); await install(resources, source); await rm(join(targetRoot, ".openbuddy-marketplace-managed.json")); await expect(resources.marketplaceAction({ type: "uninstall", sourceUrlOrPath: source, pluginRelativePath: "demo" })).rejects.toThrow(/managed/i); await expect(readFile(index, "utf8")).resolves.toContain("demo"); });
  it("keeps target and index after uninstall validation failure", async () => { const home = await mkdtemp(join(tmpdir(), "marketplace-advanced-home-")); const { resources, source, targetRoot, index } = await setup(home); await install(resources, source); await writeFile(join(targetRoot, "keep"), "yes"); await rm(join(targetRoot, ".openbuddy-marketplace-managed.json")); await expect(resources.marketplaceAction({ type: "uninstall", sourceUrlOrPath: source, pluginRelativePath: "demo" })).rejects.toThrow(); await expect(readFile(join(targetRoot, "keep"), "utf8")).resolves.toBe("yes"); await expect(readFile(index, "utf8")).resolves.toContain("demo"); });
  it("does not leave an index entry after fresh verification failure", async () => { const home = await mkdtemp(join(tmpdir(), "marketplace-advanced-home-")); const { resources, source, pluginRoot, index } = await setup(home, "fresh"); await writeFile(join(pluginRoot, "package.json"), "not-json"); await expect(install(resources, source, "fresh")).rejects.toThrow(); await expect(readFile(index, "utf8")).rejects.toMatchObject({ code: "ENOENT" }); });
  it("rejects disposed/unmanaged uninstall without mutation", async () => { const home = await mkdtemp(join(tmpdir(), "marketplace-advanced-home-")); const { resources, source, targetRoot, index } = await setup(home, "disposed"); await install(resources, source, "disposed"); await rm(join(targetRoot, ".openbuddy-marketplace-managed.json")); const before = await readFile(index, "utf8"); await expect(resources.marketplaceAction({ type: "uninstall", sourceUrlOrPath: source, pluginRelativePath: "disposed" })).rejects.toThrow(); expect(await readFile(index, "utf8")).toBe(before); await expect(lstat(targetRoot)).resolves.toBeDefined(); });
});
