import { describe, expect, it } from "vitest";
import { PluginEventLogCursorRegistry } from "../plugin-event-log-cursor";
function ready() { const registry = new PluginEventLogCursorRegistry(); const lease = registry.attachSurface("session", "panel"); if (!lease.ok) throw new Error(lease.message); return { registry, lease }; }
describe("plugin event-log cursor replay transport", () => {
  it("reads events in order and returns nextCursor", () => { const { registry, lease } = ready(); registry.append("session", "e1", { id: 1 }); registry.append("session", "e2", { id: 2 }); expect(registry.readSince("session", lease.surfaceId)).toMatchObject({ ok: true, events: [{ id: 1 }, { id: 2 }], nextCursor: "e2", truncated: false }); });
  it("keeps sinceEventId independent per surface", () => { const { registry } = ready(); registry.attachSurface("session", "web"); registry.append("session", "e1", 1); registry.append("session", "e2", 2); expect(registry.readSince("session", "panel", "e1")).toMatchObject({ events: [2], nextCursor: "e2" }); expect(registry.readSince("session", "web", undefined)).toMatchObject({ events: [1, 2], nextCursor: "e2" }); });
  it("returns a clear error after owner disposal", () => { const { registry, lease } = ready(); registry.disposeOwner("session"); expect(registry.readSince("session", lease.surfaceId)).toMatchObject({ ok: false, code: "cleared" }); });
  it("returns a clear error after the cursor freezes", () => { const { registry, lease } = ready(); registry.detachSurface("session", lease.surfaceId); expect(registry.readSince("session", lease.surfaceId)).toMatchObject({ ok: false, code: "frozen" }); });
  it("honors limit and advances nextCursor", () => { const { registry, lease } = ready(); for (const id of ["e1", "e2", "e3"]) registry.append("session", id, id); expect(registry.readSince("session", lease.surfaceId, undefined, 2)).toMatchObject({ events: ["e1", "e2"], nextCursor: "e2", truncated: true }); expect(registry.readSince("session", lease.surfaceId, "e2", 2)).toMatchObject({ events: ["e3"], nextCursor: "e3", truncated: false }); });
  it("reports a gap when sinceEventId fell out of the ring", () => { const { registry, lease } = ready(); for (let i = 0; i < 2001; i += 1) registry.append("session", `e${i}`, i); expect(registry.readSince("session", lease.surfaceId, "e0")).toMatchObject({ ok: false, code: "gap" }); });
});
