import { describe, expect, it, vi } from "vitest";
import { ReplayCoordinator } from "../../../../src/lib/agent/pi-event-replay";
describe("replay gap fallback", () => {
  it("continues without duplicate delivery", async () => { const out: unknown[] = []; const r = new ReplayCoordinator((e) => out.push(e)); await r.consumeWithFallback([{ id: "a" }], { loadHistory: async () => [] }); await r.consumeWithFallback([{ id: "a" }, { id: "b" }], { loadHistory: async () => [] }); expect(out).toHaveLength(2); });
  it("loads history on a gap", async () => { const r = new ReplayCoordinator(() => undefined); const result = await r.consumeWithFallback([{ id: "c" }], { gap: true, loadHistory: async () => [{ id: "a" }, { id: "b" }] }); expect(result).toMatchObject({ ok: true, fallback: true, events: [{ id: "a" }, { id: "b" }, { id: "c" }] }); });
  it("advances the cursor after fallback", async () => { const r = new ReplayCoordinator(() => undefined); const result = await r.consumeWithFallback([{ id: "c" }], { gap: true, loadHistory: async () => [{ id: "a" }] }); expect(result.cursor).toBe("c"); expect(r.getCursor()).toBe("c"); });
  it("does not repeat side effects for history duplicates", async () => { const dispatch = vi.fn(); const r = new ReplayCoordinator(dispatch); await r.consumeWithFallback([{ id: "b" }], { gap: true, loadHistory: async () => [{ id: "a" }, { id: "b" }] }); expect(dispatch).toHaveBeenCalledTimes(2); await r.consumeWithFallback([{ id: "b" }], { gap: true, loadHistory: async () => [{ id: "a" }] }); expect(dispatch).toHaveBeenCalledTimes(2); });
  it("returns an error without corrupting cursor when history fails", async () => { const r = new ReplayCoordinator(() => undefined); const result = await r.consumeWithFallback([{ id: "c" }], { gap: true, loadHistory: async () => { throw new Error("history unavailable"); } }); expect(result).toMatchObject({ ok: false, code: "history-fallback-failed", cursor: null }); });
  it("runs fallback telemetry only once across repeated gaps", async () => { const telemetry = vi.fn(); const r = new ReplayCoordinator(() => undefined, telemetry); await r.consumeWithFallback([{ id: "a" }], { gap: true, loadHistory: async () => [] }); await r.consumeWithFallback([{ id: "b" }], { gap: true, loadHistory: async () => [] }); expect(telemetry).toHaveBeenCalledTimes(1); });
});
