#!/usr/bin/env bash
# Wrapper around electron-builder that:
#   1. Sets the npmmirror app-builder-binaries mirror by default.
#   2. Pins a pnpm >= 11 on PATH for electron-builder's node_modules collector.
#   3. Forwards all arguments to electron-builder.
#
# Why the mirror: electron-builder downloads `app-builder-bin` from
# `github.com/develar/app-builder-bin/releases` by default, which is slow
# or unreliable from many networks (including most CN networks). The mirror
# env var must be set BEFORE electron-builder starts (it is read at
# module-load time). npm config cannot set it, so we wrap the binary.
#
# Why the pnpm pin: `app-builder-lib`'s pnpm collector branches on
# `pnpm --version`. For pnpm >= 11 every entry of `pnpm list --json` is a
# workspace package, so the collector walks all of them; for pnpm < 11 the
# output collapses to a single tree and the collector keeps only the first
# workspace package. When the surrounding toolchain PATH happens to expose a
# pnpm 10 (moon's `.moon/toolchains.yml` pin), the collector silently drops
# every sibling workspace package from the app payload — it logs
# `cannot find path for dependency` and ships an installer whose runtime dies
# with `Cannot find module 'sonic-boom'` before the window opens. The pnpm 10
# shim does not always delegate to the `packageManager` version pinned in
# package.json (delegation needs the pinned tarball in the local cache and
# fails silently in some spawn environments), so we re-expose the pinned pnpm
# explicitly via corepack and hard-fail if that is not possible: shipping a
# broken installer is worse than failing the build.
#
# Override mirrors:
#   - ELECTRON_BUILDER_BINARIES_MIRROR=https://other-mirror/path
#   - ELECTRON_MIRROR=https://other-mirror/path (also read by Electron
#     itself; electron-builder.yml also has `electronDownload.mirror`).
#
# Force the GitHub default:
#   - ELECTRON_BUILDER_BINARIES_MIRROR="" ./scripts/electron-builder.sh ...
#
# Override the pinned pnpm (must report major >= 11):
#   - OPENBUDDY_PNPM=/path/to/pnpm ./scripts/electron-builder.sh ...
#
# This script intentionally lives in scripts/ (not scripts/electron/) so
# moon task commands stay short (`./scripts/electron-builder.sh ...`).

set -euo pipefail

if [[ -z "${ELECTRON_BUILDER_BINARIES_MIRROR:-}" ]]; then
  export ELECTRON_BUILDER_BINARIES_MIRROR="https://npmmirror.com/mirrors/electron-builder-binaries/"
fi

# Resolve the local electron-builder binary so we don't depend on PATH
# inside moon's task runner.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

ELECTRON_BUILDER_BIN="${REPO_ROOT}/node_modules/.bin/electron-builder"
if [[ ! -x "${ELECTRON_BUILDER_BIN}" ]]; then
  echo "electron-builder not found at ${ELECTRON_BUILDER_BIN}; run 'pnpm install' first" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Pin pnpm >= 11 for the node_modules collector (see header).
#
# The shim lives next to the installed dependencies so repeated builds reuse
# the same file, and it is regenerated on every run so it can never go stale.
# ---------------------------------------------------------------------------
PNPM_SHIM_DIR="${REPO_ROOT}/node_modules/.openbuddy-pnpm"
PNPM_SHIM="${PNPM_SHIM_DIR}/pnpm"

pnpm_major() {
  local version
  version="$("$@" --version 2>/dev/null | tail -n 1 | tr -d '[:space:]')"
  printf '%s' "${version%%.*}"
}

write_pnpm_shim() {
  mkdir -p "${PNPM_SHIM_DIR}"
  cat > "${PNPM_SHIM}" <<SHIM
#!/bin/sh
# Generated by scripts/electron-builder.sh — do not edit by hand.
exec $1
SHIM
  chmod +x "${PNPM_SHIM}"
}

# Capture the ambient pnpm before the shim directory shadows it.
AMBIENT_PNPM="$(command -v pnpm || true)"

export PATH="${PNPM_SHIM_DIR}:${PATH}"

if [[ -n "${OPENBUDDY_PNPM:-}" ]]; then
  write_pnpm_shim "\"${OPENBUDDY_PNPM}\" \"\$@\""
elif command -v corepack >/dev/null 2>&1; then
  # corepack resolves the exact `packageManager` version from package.json,
  # with none of pnpm's own version-delegation heuristics in the way.
  write_pnpm_shim 'corepack pnpm "$@"'
elif [[ -n "${AMBIENT_PNPM}" ]]; then
  write_pnpm_shim "\"${AMBIENT_PNPM}\" \"\$@\""
else
  write_pnpm_shim 'pnpm "$@"'
fi

PNPM_MAJOR="$(pnpm_major pnpm)"
if [[ -z "${PNPM_MAJOR}" || ! "${PNPM_MAJOR}" =~ ^[0-9]+$ || "${PNPM_MAJOR}" -lt 11 ]]; then
  cat >&2 <<MSG
error: electron-builder requires pnpm >= 11 on PATH but resolved pnpm $("${PNPM_SHIM}" --version 2>/dev/null || echo '<none>').

electron-builder's node_modules collector drops every workspace package except
the first one when pnpm < 11, which produces an installer that crashes at
startup with MODULE_NOT_FOUND. Refusing to build.

Install a pnpm >= 11 (or run 'corepack enable'), or point the wrapper at one:
  OPENBUDDY_PNPM=/path/to/pnpm scripts/electron-builder.sh ...
MSG
  exit 1
fi

exec "${ELECTRON_BUILDER_BIN}" "$@"
